control_dt: 0.02

msg_type: "go"     # "hg" or "go"
imu_type: "torso"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"
# heightmap_topic: "rt/utlidar/height_map_array"
cloud_topic: "rt/utlidar/cloud"

# policy_path: "deploy/pretrain/vel_flat_go2_without.pt"
policy_path: "deploy/pretrain/navila_2000.jit"
# policy_path: "deploy/pretrain/vel_flat_go2_45_advanced_3000.pt"

# policy joint outputs mapping to real motors
# joint2motor_idx: [3,4,5,0,1,2,9,10,11,6,7,8]
# 策略模型输出到实际电机的映射
joint2motor_idx: [3,0,9,6,4,1,10,7,5,2,11,8]

# kps: [25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0] 
# kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5] 

kps: [40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0] 
kds: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 

# default_angles: [  0.1, 0.8, -1.5,
#                   -0.1, 0.8, -1.5,
#                    0.1, 1.0, -1.5,
#                   -0.1, 1.0, -1.5]
# 实际顺序
default_angles: [ -0.1, 0.8, -1.5,
                   0.1, 0.8, -1.5,
                  -0.1, 1.0, -1.5,
                   0.1, 1.0, -1.5]

action_scale: 0.25
command_scale: [1.0, 1.0, 1.0]

obs_scales_ang_vel: 1.0
obs_scales_dof_pos: 1.0
obs_scales_dof_vel: 1.0

num_actions: 12
# num_obs: 45
num_obs: 909 # 45 + 459(heightmap) + 45*9(history) = 909
history_length: 9
proprio_obs_dim: 45
full_frame_min_pts: 20000 # 凑成整圈的最少点云数
pc_cache_len: 4 # 凑成整圈的最少缓存长度
# save front camera captured images
# save_image: True
save_image: False
