policy_path: {
  high_level: "deploy/pretrain/nav_flat_go2.pt",
  low_level: "deploy/pretrain/vel_flat_go2.pt"
}
xml_path: "deploy/deploy_mujoco/robots/go2/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: {
  high_level: 100, # 5Hz
  low_level: 10 # 50Hz
}
lock_camera: False

kps: [25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0] 
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5] 

default_angles: [0.1,  0.8,  -1.5,  -0.1, 0.8, -1.5, 
                 0.1,  1.0,  -1.5,  -0.1, 1.0, -1.5] 

lin_vel_scale: 1
ang_vel_scale: 1
dof_pos_scale: 1 
dof_vel_scale: 1 
action_scale: 0.25
cmd_scale: [1, 1, 1, 1]
num_actions: 12
num_obs: {
  "high_level": 10,
  "low_level": 48
}
mapping_joints: [0, 3, 6, 9,   1, 4, 7, 10,   2, 5, 8, 11]

# TODO: customizable command controller
# [x,y,fixed_z,yaw] 
# target position x,y (mile). fixed_z is invaild. yaw in [-pi, pi] range (base frame)
cmd_init: [0.3, 0.5, 0, 1.5] 