## NOTES
# 注意将这里的参数与 isaaclab 训练时的参数对齐，部分参数对应如下：
# - kps, kds: `source/isaaclab_assets/isaaclab_assets/robots/unitree.py`下对应`stiffness`和`damping`
# - default_angles: 见`source/isaaclab_assets/isaaclab_assets/robots/unitree.py`的`init_state`
# - lin_vel_scale, ang_vel_scale, dof_pos_scale, dof_vel_scale: 见`source/isaaclab_tasks/isaaclab_tasks/manager_based/locomotion/velocity/velocity_env_cfg.py`下的`ObsTerm`，缺省为`1`
# - action_scale: `source/isaaclab_tasks/isaaclab_tasks/manager_based/locomotion/velocity/config/go2/rough_env_cfg.py`中reduce到`0.25`
# - cmd_scale: 对应`[lin_vel_x_scale, lin_vel_y_scale, ang_vel_scale]`因此缺省为`[1,1,1]`
## delete this later

# policy_path: "deploy/pretrain/navila_history_go2_5000.pt"
# policy_path: "deploy/pretrain/navila_5000.pt"
# policy_path: "deploy/pretrain/navila_kp40_kd1_standing0.2.pt"
# policy_path: "deploy/pretrain/navila_5000.jit"
policy_path: "deploy/pretrain/navila_10000.pt"
# policy_path: "deploy/pretrain/policy_base.jit"
xml_path: "deploy/deploy_mujoco/robots/go2/scene.xml"

# Total simulation time
simulation_duration: 120.0
# Simulation time step
simulation_dt: 0.002
control_dt: 0.02
control_decimation: 10
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
policy_decimation: 40
lock_camera: True

# kps: [25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0] 
# kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5] 
kps: [40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0] 
kds: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
default_angles: [0.1,  0.8,  -1.5,  -0.1, 0.8, -1.5, 
                 0.1,  1.0,  -1.5,  -0.1, 1.0, -1.5] 

lin_vel_scale: 1
ang_vel_scale: 1
dof_pos_scale: 1 
dof_vel_scale: 1 
# action_scale: 0.125
action_scale: 0.25
cmd_scale: [1, 1, 1]
num_actions: 12
# num_obs: 45
num_obs: 909
mapping_joints: [0, 3, 6, 9,   1, 4, 7, 10,   2, 5, 8, 11] # mapping joint actions to a specified order

# TODO: customizable command controller
# isaaclab default set heading_command True
# our pretrained model use heading_command True so you may retrain policy if you want to use heading_command False
# heading_command: False # using cmd_init[2] directly controll yaw speed
# heading_command: True  # use the heading_target controll target yaw (cmd_init[2] is ignored)
heading_command: True
heading_target: 0.5 # yaw target in [-pi, pi] (facing to)
heading_stiffness: 0.5

cmd_init: [0.0, 0, 0] # move forward [-1,1]
# cmd_init: [0, 0.5, 0] # pan
# cmd_init: [0, 0, 0.5] # turn around
# cmd_init: [0, 0, 0]   # stop